// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//   protoc-gen-go v1.30.0
//   protoc        v3.15.8
// source: game.proto

package v1

import (
  protoreflect "google.golang.org/protobuf/reflect/protoreflect"
  protoimpl "google.golang.org/protobuf/runtime/protoimpl"
  reflect "reflect"
  sync "sync"
)

const (
  // Verify that this generated code is sufficiently up-to-date.
  _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
  // Verify that runtime/protoimpl is sufficiently up-to-date.
  _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameType int32

const (
  GameType_UNSPECIFIED GameType = 0
  GameType_GO_9X9      GameType = 1
  GameType_GO_13X13    GameType = 2
  GameType_GO_19X19    GameType = 3
)

// Enum value maps for GameType.
var (
  GameType_name = map[int32]string{
    0: "UNSPECIFIED",
    1: "GO_9X9",
    2: "GO_13X13",
    3: "GO_19X19",
  }
  GameType_value = map[string]int32{
    "UNSPECIFIED": 0,
    "GO_9X9":      1,
    "GO_13X13":    2,
    "GO_19X19":    3,
  }
)

func (x GameType) Enum() *GameType {
  p := new(GameType)
  *p = x
  return p
}

func (x GameType) String() string {
  return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
  return file_game_proto_enumTypes[0].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
  return &file_game_proto_enumTypes[0]
}

func (x GameType) Number() protoreflect.EnumNumber {
  return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{0}
}

type GameMetadata struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  GameType GameType `protobuf:"varint,1,opt,name=game_type,json=gameType,proto3,enum=GameType" json:"game_type,omitempty"`
  GameKey  string   `protobuf:"bytes,2,opt,name=game_key,json=gameKey,proto3" json:"game_key,omitempty"`
  User1    string   `protobuf:"bytes,3,opt,name=user1,proto3" json:"user1,omitempty"`
  User2    string   `protobuf:"bytes,4,opt,name=user2,proto3" json:"user2,omitempty"`
  Moves    int32    `protobuf:"varint,5,opt,name=moves,proto3" json:"moves,omitempty"`
  Winner   int32    `protobuf:"varint,6,opt,name=winner,proto3" json:"winner,omitempty"`
}

func (x *GameMetadata) Reset() {
  *x = GameMetadata{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[0]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *GameMetadata) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*GameMetadata) ProtoMessage() {}

func (x *GameMetadata) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[0]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use GameMetadata.ProtoReflect.Descriptor instead.
func (*GameMetadata) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameMetadata) GetGameType() GameType {
  if x != nil {
    return x.GameType
  }
  return GameType_UNSPECIFIED
}

func (x *GameMetadata) GetGameKey() string {
  if x != nil {
    return x.GameKey
  }
  return ""
}

func (x *GameMetadata) GetUser1() string {
  if x != nil {
    return x.User1
  }
  return ""
}

func (x *GameMetadata) GetUser2() string {
  if x != nil {
    return x.User2
  }
  return ""
}

func (x *GameMetadata) GetMoves() int32 {
  if x != nil {
    return x.Moves
  }
  return 0
}

func (x *GameMetadata) GetWinner() int32 {
  if x != nil {
    return x.Winner
  }
  return 0
}

type GameState struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  Board         string `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
  Moves         int32  `protobuf:"varint,2,opt,name=moves,proto3" json:"moves,omitempty"`
  Winner        int32  `protobuf:"varint,3,opt,name=winner,proto3" json:"winner,omitempty"`
  LastMove      int32  `protobuf:"varint,4,opt,name=last_move,json=lastMove,proto3" json:"last_move,omitempty"`
  PenultMove    int32  `protobuf:"varint,5,opt,name=penult_move,json=penultMove,proto3" json:"penult_move,omitempty"`
  Player1Online bool   `protobuf:"varint,6,opt,name=player1Online,proto3" json:"player1Online,omitempty"`
  Player2Online bool   `protobuf:"varint,7,opt,name=player2Online,proto3" json:"player2Online,omitempty"`
}

func (x *GameState) Reset() {
  *x = GameState{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[1]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *GameState) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[1]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameState) GetBoard() string {
  if x != nil {
    return x.Board
  }
  return ""
}

func (x *GameState) GetMoves() int32 {
  if x != nil {
    return x.Moves
  }
  return 0
}

func (x *GameState) GetWinner() int32 {
  if x != nil {
    return x.Winner
  }
  return 0
}

func (x *GameState) GetLastMove() int32 {
  if x != nil {
    return x.LastMove
  }
  return 0
}

func (x *GameState) GetPenultMove() int32 {
  if x != nil {
    return x.PenultMove
  }
  return 0
}

func (x *GameState) GetPlayer1Online() bool {
  if x != nil {
    return x.Player1Online
  }
  return false
}

func (x *GameState) GetPlayer2Online() bool {
  if x != nil {
    return x.Player2Online
  }
  return false
}

type CreateGameRequest struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  GameType  GameType `protobuf:"varint,1,opt,name=game_type,json=gameType,proto3,enum=GameType" json:"game_type,omitempty"`
  OtherUser string   `protobuf:"bytes,2,opt,name=other_user,json=otherUser,proto3" json:"other_user,omitempty"`
  // Types that are assignable to GameData:
  //
  //  *CreateGameRequest_Go
  GameData isCreateGameRequest_GameData `protobuf_oneof:"game_data"`
}

func (x *CreateGameRequest) Reset() {
  *x = CreateGameRequest{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[2]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *CreateGameRequest) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[2]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGameRequest) GetGameType() GameType {
  if x != nil {
    return x.GameType
  }
  return GameType_UNSPECIFIED
}

func (x *CreateGameRequest) GetOtherUser() string {
  if x != nil {
    return x.OtherUser
  }
  return ""
}

func (m *CreateGameRequest) GetGameData() isCreateGameRequest_GameData {
  if m != nil {
    return m.GameData
  }
  return nil
}

func (x *CreateGameRequest) GetGo() *CreateGoGameRequest {
  if x, ok := x.GetGameData().(*CreateGameRequest_Go); ok {
    return x.Go
  }
  return nil
}

type isCreateGameRequest_GameData interface {
  isCreateGameRequest_GameData()
}

type CreateGameRequest_Go struct {
  Go *CreateGoGameRequest `protobuf:"bytes,3,opt,name=go,proto3,oneof"`
}

func (*CreateGameRequest_Go) isCreateGameRequest_GameData() {}

type CreateGameResponse struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  GameType GameType `protobuf:"varint,1,opt,name=game_type,json=gameType,proto3,enum=GameType" json:"game_type,omitempty"`
  GameKey  string   `protobuf:"bytes,2,opt,name=game_key,json=gameKey,proto3" json:"game_key,omitempty"`
  // Types that are assignable to GameData:
  //
  //  *CreateGameResponse_Go
  GameData isCreateGameResponse_GameData `protobuf_oneof:"game_data"`
}

func (x *CreateGameResponse) Reset() {
  *x = CreateGameResponse{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[3]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *CreateGameResponse) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[3]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGameResponse) GetGameType() GameType {
  if x != nil {
    return x.GameType
  }
  return GameType_UNSPECIFIED
}

func (x *CreateGameResponse) GetGameKey() string {
  if x != nil {
    return x.GameKey
  }
  return ""
}

func (m *CreateGameResponse) GetGameData() isCreateGameResponse_GameData {
  if m != nil {
    return m.GameData
  }
  return nil
}

func (x *CreateGameResponse) GetGo() *CreateGoGameResponse {
  if x, ok := x.GetGameData().(*CreateGameResponse_Go); ok {
    return x.Go
  }
  return nil
}

type isCreateGameResponse_GameData interface {
  isCreateGameResponse_GameData()
}

type CreateGameResponse_Go struct {
  Go *CreateGoGameResponse `protobuf:"bytes,3,opt,name=go,proto3,oneof"`
}

func (*CreateGameResponse_Go) isCreateGameResponse_GameData() {}

type CreateGoGameRequest struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  CreatorGoesFirst bool `protobuf:"varint,3,opt,name=creator_goes_first,json=creatorGoesFirst,proto3" json:"creator_goes_first,omitempty"`
}

func (x *CreateGoGameRequest) Reset() {
  *x = CreateGoGameRequest{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[4]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *CreateGoGameRequest) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoGameRequest) ProtoMessage() {}

func (x *CreateGoGameRequest) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[4]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use CreateGoGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGoGameRequest) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGoGameRequest) GetCreatorGoesFirst() bool {
  if x != nil {
    return x.CreatorGoesFirst
  }
  return false
}

type CreateGoGameResponse struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields
}

func (x *CreateGoGameResponse) Reset() {
  *x = CreateGoGameResponse{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[5]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *CreateGoGameResponse) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoGameResponse) ProtoMessage() {}

func (x *CreateGoGameResponse) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[5]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use CreateGoGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGoGameResponse) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{5}
}

type GetGamesRequest struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields
}

func (x *GetGamesRequest) Reset() {
  *x = GetGamesRequest{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[6]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *GetGamesRequest) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesRequest) ProtoMessage() {}

func (x *GetGamesRequest) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[6]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use GetGamesRequest.ProtoReflect.Descriptor instead.
func (*GetGamesRequest) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{6}
}

type GetGamesResponse struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  Games []*GameMetadata `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *GetGamesResponse) Reset() {
  *x = GetGamesResponse{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[7]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *GetGamesResponse) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesResponse) ProtoMessage() {}

func (x *GetGamesResponse) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[7]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use GetGamesResponse.ProtoReflect.Descriptor instead.
func (*GetGamesResponse) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *GetGamesResponse) GetGames() []*GameMetadata {
  if x != nil {
    return x.Games
  }
  return nil
}

type GetSpectatorGamesRequest struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields
}

func (x *GetSpectatorGamesRequest) Reset() {
  *x = GetSpectatorGamesRequest{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[8]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *GetSpectatorGamesRequest) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*GetSpectatorGamesRequest) ProtoMessage() {}

func (x *GetSpectatorGamesRequest) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[8]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use GetSpectatorGamesRequest.ProtoReflect.Descriptor instead.
func (*GetSpectatorGamesRequest) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{8}
}

type GetSpectatorGamesResponse struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  Games []*GameMetadata `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *GetSpectatorGamesResponse) Reset() {
  *x = GetSpectatorGamesResponse{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[9]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *GetSpectatorGamesResponse) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*GetSpectatorGamesResponse) ProtoMessage() {}

func (x *GetSpectatorGamesResponse) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[9]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use GetSpectatorGamesResponse.ProtoReflect.Descriptor instead.
func (*GetSpectatorGamesResponse) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *GetSpectatorGamesResponse) GetGames() []*GameMetadata {
  if x != nil {
    return x.Games
  }
  return nil
}

type MoveGoRequest struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  GameKey  string `protobuf:"bytes,1,opt,name=game_key,json=gameKey,proto3" json:"game_key,omitempty"`
  MoveFrom int32  `protobuf:"varint,2,opt,name=move_from,json=moveFrom,proto3" json:"move_from,omitempty"`
  MoveTo   int32  `protobuf:"varint,3,opt,name=move_to,json=moveTo,proto3" json:"move_to,omitempty"`
}

func (x *MoveGoRequest) Reset() {
  *x = MoveGoRequest{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[10]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *MoveGoRequest) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*MoveGoRequest) ProtoMessage() {}

func (x *MoveGoRequest) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[10]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use MoveGoRequest.ProtoReflect.Descriptor instead.
func (*MoveGoRequest) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *MoveGoRequest) GetGameKey() string {
  if x != nil {
    return x.GameKey
  }
  return ""
}

func (x *MoveGoRequest) GetMoveFrom() int32 {
  if x != nil {
    return x.MoveFrom
  }
  return 0
}

func (x *MoveGoRequest) GetMoveTo() int32 {
  if x != nil {
    return x.MoveTo
  }
  return 0
}

type StateGoResponse struct {
  state         protoimpl.MessageState
  sizeCache     protoimpl.SizeCache
  unknownFields protoimpl.UnknownFields

  GameState        *GameState `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
  P1StonesCaptured int32      `protobuf:"varint,2,opt,name=p1_stones_captured,json=p1StonesCaptured,proto3" json:"p1_stones_captured,omitempty"`
  P2StonesCaptured int32      `protobuf:"varint,3,opt,name=p2_stones_captured,json=p2StonesCaptured,proto3" json:"p2_stones_captured,omitempty"`
  P1Score          int32      `protobuf:"varint,4,opt,name=p1_score,json=p1Score,proto3" json:"p1_score,omitempty"`
  P2Score          int32      `protobuf:"varint,5,opt,name=p2_score,json=p2Score,proto3" json:"p2_score,omitempty"`
}

func (x *StateGoResponse) Reset() {
  *x = StateGoResponse{}
  if protoimpl.UnsafeEnabled {
    mi := &file_game_proto_msgTypes[11]
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    ms.StoreMessageInfo(mi)
  }
}

func (x *StateGoResponse) String() string {
  return protoimpl.X.MessageStringOf(x)
}

func (*StateGoResponse) ProtoMessage() {}

func (x *StateGoResponse) ProtoReflect() protoreflect.Message {
  mi := &file_game_proto_msgTypes[11]
  if protoimpl.UnsafeEnabled && x != nil {
    ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
    if ms.LoadMessageInfo() == nil {
      ms.StoreMessageInfo(mi)
    }
    return ms
  }
  return mi.MessageOf(x)
}

// Deprecated: Use StateGoResponse.ProtoReflect.Descriptor instead.
func (*StateGoResponse) Descriptor() ([]byte, []int) {
  return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *StateGoResponse) GetGameState() *GameState {
  if x != nil {
    return x.GameState
  }
  return nil
}

func (x *StateGoResponse) GetP1StonesCaptured() int32 {
  if x != nil {
    return x.P1StonesCaptured
  }
  return 0
}

func (x *StateGoResponse) GetP2StonesCaptured() int32 {
  if x != nil {
    return x.P2StonesCaptured
  }
  return 0
}

func (x *StateGoResponse) GetP1Score() int32 {
  if x != nil {
    return x.P1Score
  }
  return 0
}

func (x *StateGoResponse) GetP2Score() int32 {
  if x != nil {
    return x.P2Score
  }
  return 0
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
  0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a,
  0x0c, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a,
  0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
  0x32, 0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x67, 0x61, 0x6d,
  0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6b, 0x65,
  0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x4b, 0x65, 0x79,
  0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
  0x05, 0x75, 0x73, 0x65, 0x72, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x32, 0x18,
  0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x32, 0x12, 0x14, 0x0a, 0x05,
  0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x76,
  0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
  0x28, 0x05, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0xd9, 0x01, 0x0a, 0x09, 0x47,
  0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72,
  0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14,
  0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
  0x6f, 0x76, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03,
  0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09,
  0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
  0x08, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x65, 0x6e,
  0x75, 0x6c, 0x74, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
  0x70, 0x65, 0x6e, 0x75, 0x6c, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6c,
  0x61, 0x79, 0x65, 0x72, 0x31, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
  0x08, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
  0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
  0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32,
  0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
  0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x09,
  0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
  0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65,
  0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x75, 0x73,
  0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x55,
  0x73, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x02, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
  0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
  0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x02, 0x67, 0x6f, 0x42, 0x0b, 0x0a, 0x09, 0x67,
  0x61, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8d, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65,
  0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
  0x26, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
  0x28, 0x0e, 0x32, 0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x67,
  0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f,
  0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x4b,
  0x65, 0x79, 0x12, 0x27, 0x0a, 0x02, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
  0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
  0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x02, 0x67, 0x6f, 0x42, 0x0b, 0x0a, 0x09, 0x67,
  0x61, 0x6d, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
  0x74, 0x65, 0x47, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
  0x2c, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x67, 0x6f, 0x65, 0x73, 0x5f,
  0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x63, 0x72, 0x65,
  0x61, 0x74, 0x6f, 0x72, 0x47, 0x6f, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x22, 0x16, 0x0a,
  0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
  0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65,
  0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47,
  0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05,
  0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x61,
  0x6d, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65,
  0x73, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f,
  0x72, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a,
  0x19, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x47, 0x61, 0x6d,
  0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x67, 0x61,
  0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x61, 0x6d, 0x65,
  0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22,
  0x60, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x47, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
  0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
  0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
  0x6f, 0x76, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
  0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x65,
  0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x65, 0x54,
  0x6f, 0x22, 0xce, 0x01, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x52, 0x65, 0x73,
  0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74,
  0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x47, 0x61, 0x6d, 0x65,
  0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
  0x12, 0x2c, 0x0a, 0x12, 0x70, 0x31, 0x5f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x63, 0x61,
  0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x70, 0x31,
  0x53, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x12, 0x2c,
  0x0a, 0x12, 0x70, 0x32, 0x5f, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x63, 0x61, 0x70, 0x74,
  0x75, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x70, 0x32, 0x53, 0x74,
  0x6f, 0x6e, 0x65, 0x73, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08,
  0x70, 0x31, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
  0x70, 0x31, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x32, 0x5f, 0x73, 0x63,
  0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x32, 0x53, 0x63, 0x6f,
  0x72, 0x65, 0x2a, 0x43, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f,
  0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
  0x0a, 0x0a, 0x06, 0x47, 0x4f, 0x5f, 0x39, 0x58, 0x39, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x47,
  0x4f, 0x5f, 0x31, 0x33, 0x58, 0x31, 0x33, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x4f, 0x5f,
  0x31, 0x39, 0x58, 0x31, 0x39, 0x10, 0x03, 0x32, 0x45, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
  0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
  0x61, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
  0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
  0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x3d,
  0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x08, 0x47, 0x65,
  0x74, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65,
  0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61,
  0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x61, 0x0a,
  0x11, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x47, 0x61, 0x6d,
  0x65, 0x73, 0x12, 0x4c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74,
  0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65,
  0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
  0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f,
  0x72, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
  0x32, 0x36, 0x0a, 0x02, 0x47, 0x6f, 0x12, 0x30, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x6f,
  0x12, 0x0e, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x47, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
  0x1a, 0x10, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x47, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
  0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x31, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e,
  0x6e, 0x66, 0x65, 0x68, 0x73, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x67, 0x61, 0x6d,
  0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x62, 0x73, 0x42, 0x09, 0x47, 0x61, 0x6d, 0x65,
  0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x04, 0x2e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
  0x74, 0x6f, 0x33,
}

var (
  file_game_proto_rawDescOnce sync.Once
  file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
  file_game_proto_rawDescOnce.Do(func() {
    file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
  })
  return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_game_proto_goTypes = []interface{}{
  (GameType)(0),                     // 0: GameType
  (*GameMetadata)(nil),              // 1: GameMetadata
  (*GameState)(nil),                 // 2: GameState
  (*CreateGameRequest)(nil),         // 3: CreateGameRequest
  (*CreateGameResponse)(nil),        // 4: CreateGameResponse
  (*CreateGoGameRequest)(nil),       // 5: CreateGoGameRequest
  (*CreateGoGameResponse)(nil),      // 6: CreateGoGameResponse
  (*GetGamesRequest)(nil),           // 7: GetGamesRequest
  (*GetGamesResponse)(nil),          // 8: GetGamesResponse
  (*GetSpectatorGamesRequest)(nil),  // 9: GetSpectatorGamesRequest
  (*GetSpectatorGamesResponse)(nil), // 10: GetSpectatorGamesResponse
  (*MoveGoRequest)(nil),             // 11: MoveGoRequest
  (*StateGoResponse)(nil),           // 12: StateGoResponse
}
var file_game_proto_depIdxs = []int32{
  0,  // 0: GameMetadata.game_type:type_name -> GameType
  0,  // 1: CreateGameRequest.game_type:type_name -> GameType
  5,  // 2: CreateGameRequest.go:type_name -> CreateGoGameRequest
  0,  // 3: CreateGameResponse.game_type:type_name -> GameType
  6,  // 4: CreateGameResponse.go:type_name -> CreateGoGameResponse
  1,  // 5: GetGamesResponse.games:type_name -> GameMetadata
  1,  // 6: GetSpectatorGamesResponse.games:type_name -> GameMetadata
  2,  // 7: StateGoResponse.game_state:type_name -> GameState
  3,  // 8: CreateGame.CreateGame:input_type -> CreateGameRequest
  7,  // 9: GetGames.GetGames:input_type -> GetGamesRequest
  9,  // 10: GetSpectatorGames.GetSpectatorGames:input_type -> GetSpectatorGamesRequest
  11, // 11: Go.PlayGo:input_type -> MoveGoRequest
  4,  // 12: CreateGame.CreateGame:output_type -> CreateGameResponse
  8,  // 13: GetGames.GetGames:output_type -> GetGamesResponse
  10, // 14: GetSpectatorGames.GetSpectatorGames:output_type -> GetSpectatorGamesResponse
  12, // 15: Go.PlayGo:output_type -> StateGoResponse
  12, // [12:16] is the sub-list for method output_type
  8,  // [8:12] is the sub-list for method input_type
  8,  // [8:8] is the sub-list for extension type_name
  8,  // [8:8] is the sub-list for extension extendee
  0,  // [0:8] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
  if File_game_proto != nil {
    return
  }
  if !protoimpl.UnsafeEnabled {
    file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*GameMetadata); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*GameState); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*CreateGameRequest); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*CreateGameResponse); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*CreateGoGameRequest); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*CreateGoGameResponse); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*GetGamesRequest); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*GetGamesResponse); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*GetSpectatorGamesRequest); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*GetSpectatorGamesResponse); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*MoveGoRequest); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
    file_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
      switch v := v.(*StateGoResponse); i {
      case 0:
        return &v.state
      case 1:
        return &v.sizeCache
      case 2:
        return &v.unknownFields
      default:
        return nil
      }
    }
  }
  file_game_proto_msgTypes[2].OneofWrappers = []interface{}{
    (*CreateGameRequest_Go)(nil),
  }
  file_game_proto_msgTypes[3].OneofWrappers = []interface{}{
    (*CreateGameResponse_Go)(nil),
  }
  type x struct{}
  out := protoimpl.TypeBuilder{
    File: protoimpl.DescBuilder{
      GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
      RawDescriptor: file_game_proto_rawDesc,
      NumEnums:      1,
      NumMessages:   12,
      NumExtensions: 0,
      NumServices:   4,
    },
    GoTypes:           file_game_proto_goTypes,
    DependencyIndexes: file_game_proto_depIdxs,
    EnumInfos:         file_game_proto_enumTypes,
    MessageInfos:      file_game_proto_msgTypes,
  }.Build()
  File_game_proto = out.File
  file_game_proto_rawDesc = nil
  file_game_proto_goTypes = nil
  file_game_proto_depIdxs = nil
}
