{{- if .Values.librarygames.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "librarygames.serviceAccountName" . }}
  labels:
    {{- include "librarygames.labels" . | nindent 4 }}
  {{- with .Values.librarygames.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
