apiVersion: v1
kind: Service
metadata:
  name: {{ include "librarygames.fullname" . }}
  labels:
    {{- include "librarygames.labels" . | nindent 4 }}
spec:
  type: {{ .Values.librarygames.service.type }}
  ports:
    - port: {{ .Values.librarygames.service.port }}
      targetPort: games
      protocol: UDP
      name: games
  selector:
    {{- include "librarygames.selectorLabels" . | nindent 4 }}
