---
# Default values for sonarqube deployed on minikube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

account:
  currentAdminPassword: admin
  adminPassword: hi
persistence:
  enabled: true
service:
  type: NodePort
