apiVersion: v2
appVersion: "1.1.1"
dependencies:
  - condition: global.mysql.enabled
    name: mysql
    version: 9.9.1
    repository: https://charts.bitnami.com/bitnami
description: A Helm chart for running a librarygames backend on Kubernetes
name: librarygames
type: application
version: 0.1.0
